### ISSUE TITLE
Adding a new Commcare build takes one to an empty Jenkins build pipeline

### ISSUE THREAD

**Issue by dirkdejager** [dimagi/commcare-cloud#4673]
I am trying to follow the instructions to setup a server to "Add a new CommCare build" / Step 8 on the instructions here: 
https://github.com/dimagi/commcare-cloud/blob/master/docs/setup/new_environment.md#add-a-new-commcare-build

Unfortunately, when attempting to follow Step 1: browse builds on the Jenkins server, there are no builds present (See Figure 1).

![image](https://user-images.githubusercontent.com/1805949/115194143-547b6b80-a0ed-11eb-9012-b553c6e29777.png)

Is there something I am doing wrong? Or should the link be updated somehow?

Thanks,

Dirk

**Comment by snopoke** [comment]
@dirkdejager hello!

I haven't added a new build except locally for testing in a very long time but I'll find out and get back to you.

**Comment by snopoke** [comment]
Hi @dirkdejager 

Turns out we already have a ticket to revamp this process now that we don't support J2ME devices any more. The basic process you can follow is:

1. Navigate to https://github.com/dimagi/commcare-android/releases to find the latest release number
2. Enter the release number in the "version" field of the form
3. Make up a build number (must be an integer) - this field isn't really used for anything.
4. Leave the "Source for artifacts.zip" blank.

I hope that unblocks you.

**Comment by dirkdejager** [comment]
Brilliant! Thank you very much, this helped solve the problem
