### ISSUE TITLE
Fresh install fails on task "Get current formplayer release"

### ISSUE THREAD

**Issue by zwets** [dimagi/commcare-cloud#6401]
Merged pull request #6395 from yesterday breaks fresh installs.

See this comment: [6fe6169](https://github.com/dimagi/commcare-cloud/commit/6fe616921bc4a3f31861a1cc6fba768dc05ae11f#commitcomment-147827812)

Best wishes,
Marco

**Comment by gherceg** [comment]
Hi @zwets. Thanks for creating the issue.

Requoting your initial comment.

> This commit breaks a fresh install. Line 170 in main.yml has
>
>readlink {{ formplayer_current_dir }})-{{ env_monitoring_id }}
>
>On a fresh install, {{ formplayer_current_dir }} is empty (there isn't a current symlink yet), so this evaluates to
>
>readlink -something
>
>So readlink will parse the -something as a commandline option and fail.

Based on the [main vars file](https://github.com/dimagi/commcare-cloud/blob/bc5cf52613bf0c401c869c00f5bfc084273188a0/src/commcare_cloud/ansible/roles/formplayer/vars/main.yml#L11-L11), I'd expect `formplayer_current_dir` to never be empty, which would mean you shouldn't run into an issue with the `readlink` command failing due to strange formatting (i.e. `readlink -something`). However given that the symlink has not yet been created, `readlink /path/to/current/release` would return an empty string, causing `basename` to fail. Am I missing something there? 

I've put up [a PR](https://github.com/dimagi/commcare-cloud/pull/6402) to resolve my understanding of the issue, but please let me know if you still have concerns.

**Comment by gherceg** [comment]
@zwets [the PR](https://github.com/dimagi/commcare-cloud/pull/6402) has been merged into the master branch. Thanks again for creating this issue.

**Comment by zwets** [comment]
Thanks Graham, happy to contribute!
